import type { Database } from './domain'

export const seedDatabase: Database = {
  staff: [
    { id: 'staff-founder', name: '林砚', role: 'ADMIN', permissionRole: 'ADMIN', status: 'ACTIVE', loginEnabled: true, displayRole: '管理员', title: '管理员', phone: '15021512537', specialty: '经营与服务设计', avatar: '林' },
    { id: 'staff-admin', name: '苏棠', role: 'ADMIN', permissionRole: 'ADMIN', status: 'ACTIVE', loginEnabled: true, displayRole: '管理员', title: '管理员', phone: '15021512538', specialty: '客户运营', avatar: '苏' },
    { id: 'mentor-zhang', name: '周予安', role: 'MENTOR', permissionRole: 'MENTOR', status: 'ACTIVE', loginEnabled: false, displayRole: '导师', title: '导师', phone: '15021512539', specialty: '关系与人生方向', avatar: '周' },
    { id: 'mentor-li', name: '沈知夏', role: 'MENTOR', permissionRole: 'MENTOR', status: 'ACTIVE', loginEnabled: false, displayRole: '导师', title: '导师', phone: '15021512540', specialty: '表达与主体性', avatar: '沈' },
    { id: 'mentor-qiao', name: '顾南枝', role: 'MENTOR', permissionRole: 'MENTOR', status: 'ACTIVE', loginEnabled: false, displayRole: '导师', title: '导师', phone: '15021512541', specialty: '职业转型与行动', avatar: '顾' },
    { id: 'mentor-chen', name: '贺闻舟', role: 'MENTOR', permissionRole: 'MENTOR', status: 'ACTIVE', loginEnabled: false, displayRole: '导师', title: '导师', phone: '15021512542', specialty: '情绪稳定与自我关系', avatar: '贺' },
  ],
  customers: [
    {
      id: 'C00001298', createdAt: '2026-09-20', name: '林知微', initials: '林', phone: '138****1212', status: '活跃', grade: 'A', gradeSource: '导师确认', mentorId: 'mentor-zhang', referrerName: '',
      need: '离婚后生活重建，同时伴随职业方向迷茫。', helpExpectation: '希望有人陪我把接下来的路理一理。', goal: '未来 3 个月重新恢复稳定生活节奏，并逐步确认职业方向。', brief: '近期经历婚姻关系变化，同时对未来生活和事业方向感到迷茫。接待时先确认当前最紧迫的问题，再了解日常生活是否受到明显影响。', intendedCourse: '觉塑',
      confirmedFacts: ['最近经历婚姻关系变化', '正在考虑职业调整', '主动表达希望获得持续支持'],
      aiQuestions: ['是否愿意进入系统性成长服务', '当前时间与投入条件'], paid: true, lastActivity: '今天 10:40', nextFollowup: '2026-10-06', lastFollowupAt: '2026-10-04', nextFollowupAt: '2026-10-06', followupStatus: '跟进中', notes: '先关注生活节奏恢复，不急着介绍课程。',
    },
    {
      id: 'C00001301', createdAt: '2026-09-28', name: '沈嘉禾', initials: '沈', phone: '139****4431', status: '活跃', grade: 'B', gradeSource: 'AI建议', mentorId: 'mentor-zhang', referrerName: '',
      need: '与伴侣沟通反复陷入争执，想先找到更有效的表达方式。', helpExpectation: '想先学习一次不升级冲突的沟通。', goal: '减少冲突升级，建立一套双方都能执行的沟通习惯。', brief: '用户希望先从一次具体的沟通练习开始，不建议一开始扩大到完整的关系诊断。', intendedCourse: '镜像技术',
      confirmedFacts: ['最近一周发生两次激烈争执', '愿意尝试记录触发点'], aiQuestions: ['是否愿意一起参与关系练习'], paid: false, lastActivity: '昨天 16:20', nextFollowup: '2026-10-04',
      lastFollowupAt: '2026-10-03', nextFollowupAt: '2026-10-04', followupStatus: '待跟进', notes: '先做一次不升级冲突的沟通练习。',
    },
    {
      id: 'C00001276', createdAt: '2026-09-15', name: '许清和', initials: '许', phone: '137****2208', status: '待激活', grade: 'A', gradeSource: '导师确认', mentorId: 'mentor-li', referrerName: '',
      need: '希望从长期自我怀疑中走出来，重新建立行动感。', helpExpectation: '想找到能真正开始的方法。', goal: '把“想做的事”拆成可以开始的具体行动。', brief: '用户对“有人陪着完成第一步”有明确需求，本次优先确认上周行动后的变化。', intendedCourse: '镜像技术',
      confirmedFacts: ['已经完成一次觉塑体验', '上次提到想重新开始学习'], aiQuestions: ['上周约定的行动是否有变化'], paid: true, lastActivity: '3 天前', nextFollowup: '2026-10-04',
      lastFollowupAt: '2026-10-01', nextFollowupAt: '2026-10-04', followupStatus: '待跟进', notes: '确认上周行动后的变化。',
    },
    {
      id: 'C00001305', createdAt: '2026-10-04', name: '叶承安', initials: '叶', phone: '136****9087', status: '活跃', grade: 'C', gradeSource: 'AI建议', mentorId: null, referrerName: '',
      need: '刚刚开始了解 ASVA，希望先获得一次轻量沟通。', helpExpectation: '希望先获得一次轻量沟通。', goal: '厘清当前最想解决的一件事。', brief: '来自解忧小屋的首次预约，先让用户把问题说清楚，不急着做课程判断。', intendedCourse: null,
      confirmedFacts: ['来自解忧小屋预约', '倾向文字沟通'], aiQuestions: ['是否存在明确的长期目标'], paid: false, lastActivity: '20 分钟前', nextFollowup: null,
      lastFollowupAt: null, nextFollowupAt: null, followupStatus: '待跟进', notes: '',
    },
    {
      id: 'C00001254', createdAt: '2026-08-18', name: '唐若宁', initials: '唐', phone: '135****7819', status: '已完成', grade: 'S', gradeSource: '导师确认', mentorId: 'mentor-li', referrerName: '',
      need: '希望在职业转型期获得持续的外部支持。', helpExpectation: '希望在职业转型期获得持续的外部支持。', goal: '完成从想法到作品集的第一轮验证。', brief: '已完成一期课程，当前重点是确认长期学习和社群支持的真实需求。', intendedCourse: '长期成长社群',
      confirmedFacts: ['已完成镜像技术一期', '主动询问长期社群'], aiQuestions: [], paid: true, lastActivity: '9 月 28 日', nextFollowup: null,
      lastFollowupAt: '2026-09-28', nextFollowupAt: null, followupStatus: '已完成', notes: '已完成一期镜像技术。',
    },
    {
      id: 'C00001306', createdAt: '2026-10-04', name: '苏晚晴', initials: '苏', phone: '150****2601', status: '活跃', grade: 'C', gradeSource: 'AI建议', mentorId: null, referrerName: '',
      need: '工作几年后开始怀疑自己是不是走错了方向。', helpExpectation: '想有人帮我把纠结的几件事拆开。', goal: '先确定接下来一个月可以验证的方向。', brief: '首次预约，当前更适合从具体困惑入手，帮助客户把模糊的焦虑说成可讨论的问题。', intendedCourse: null,
      confirmedFacts: ['最近在考虑换行业', '希望先做一次梳理'], aiQuestions: ['目前最想改变的是工作内容还是生活节奏'], paid: false, lastActivity: '今天 09:20', nextFollowup: null,
      lastFollowupAt: null, nextFollowupAt: null, followupStatus: '待跟进', notes: '',
    },
    {
      id: 'C00001307', createdAt: '2026-10-04', name: '贺言川', initials: '贺', phone: '150****2602', status: '活跃', grade: 'C', gradeSource: 'AI建议', mentorId: null, referrerName: '',
      need: '长期拖延重要的事，越拖越不敢开始。', helpExpectation: '希望找到一个今天就能开始的行动。', goal: '建立一套低压力的启动方式。', brief: '客户的表达集中在“开始困难”，接待时优先确认具体场景与身体感受，不急于给出方法清单。', intendedCourse: null,
      confirmedFacts: ['已经尝试过待办清单', '愿意从小行动开始'], aiQuestions: ['最容易卡住的时间段是什么'], paid: false, lastActivity: '今天 09:45', nextFollowup: null,
      lastFollowupAt: null, nextFollowupAt: null, followupStatus: '待跟进', notes: '',
    },
    {
      id: 'C00001308', createdAt: '2026-10-03', name: '顾栖迟', initials: '顾', phone: '150****2603', status: '活跃', grade: 'B', gradeSource: '导师确认', mentorId: 'mentor-qiao', referrerName: '林知微',
      need: '准备离开熟悉的行业，但对新选择没有把握。', helpExpectation: '想把转型计划变得更具体。', goal: '完成一次能力盘点并确定验证路径。', brief: '客户已完成初步沟通，当前重点是把“想转型”落到可验证的岗位和行动上。', intendedCourse: '东方领导力',
      confirmedFacts: ['已有三年项目管理经验', '正在收集新行业信息'], aiQuestions: ['愿意投入多少时间进行转型验证'], paid: false, lastActivity: '今天 11:15', nextFollowup: '2026-10-07',
      lastFollowupAt: '2026-10-03', nextFollowupAt: '2026-10-07', followupStatus: '跟进中', notes: '下一次确认能力盘点结果。',
    },
    {
      id: 'C00001309', createdAt: '2026-10-02', name: '江予墨', initials: '江', phone: '150****2604', status: '活跃', grade: 'A', gradeSource: '导师确认', mentorId: 'mentor-zhang', referrerName: '',
      need: '和家人沟通时总是先防御，事后又觉得可惜。', helpExpectation: '希望练习更稳定地表达边界。', goal: '减少对话中的自动反应，保留关系里的选择感。', brief: '客户已经能识别部分触发点，接待时可以围绕一次具体对话做复盘和练习。', intendedCourse: '镜像技术',
      confirmedFacts: ['能回忆一次典型冲突', '愿意尝试新的表达方式'], aiQuestions: ['家人是否愿意参与后续练习'], paid: false, lastActivity: '昨天 18:10', nextFollowup: '2026-10-06',
      lastFollowupAt: '2026-10-02', nextFollowupAt: '2026-10-06', followupStatus: '跟进中', notes: '从最近一次家庭对话开始。',
    },
    {
      id: 'C00001310', createdAt: '2026-10-01', name: '温知行', initials: '温', phone: '150****2605', status: '活跃', grade: 'B', gradeSource: '导师确认', mentorId: 'mentor-chen', referrerName: '',
      need: '最近情绪起伏明显，工作时很难集中。', helpExpectation: '希望找到让自己先稳定下来的方法。', goal: '识别情绪波动前的信号并建立应对动作。', brief: '已完成一次真人沟通，当前适合先整理触发场景与可执行的稳定动作。', intendedCourse: '觉塑',
      confirmedFacts: ['睡眠节奏最近不稳定', '愿意记录情绪变化'], aiQuestions: ['哪一种场景最需要优先处理'], paid: true, lastActivity: '昨天 15:40', nextFollowup: '2026-10-05',
      lastFollowupAt: '2026-10-01', nextFollowupAt: '2026-10-05', followupStatus: '待跟进', notes: '等待导师补充本次沟通记录。',
    },
    {
      id: 'C00001311', createdAt: '2026-09-22', name: '陆星遥', initials: '陆', phone: '150****2606', status: '已完成', grade: 'A', gradeSource: '导师确认', mentorId: 'mentor-qiao', referrerName: '',
      need: '完成一次职业方向梳理，准备开始新的项目。', helpExpectation: '希望确认行动节奏和优先级。', goal: '完成新项目第一阶段的验证。', brief: '客户已经完成一轮方向梳理，当前信息足够进入行动阶段。', intendedCourse: '东方领导力',
      confirmedFacts: ['已确定项目主题', '已经开始联系合作伙伴'], aiQuestions: [], paid: true, lastActivity: '9 月 30 日', nextFollowup: null,
      lastFollowupAt: '2026-09-30', nextFollowupAt: null, followupStatus: '已完成', notes: '本轮服务已完成。',
    },
    {
      id: 'C00001312', createdAt: '2026-10-04', name: '白芷宁', initials: '白', phone: '150****2607', status: '活跃', grade: 'C', gradeSource: 'AI建议', mentorId: null, referrerName: '',
      need: '从团队管理岗位离开后，对下一步选择很犹豫。', helpExpectation: '想先把自己真正想要的生活方式说清楚。', goal: '厘清职业选择背后的真实需求。', brief: '来自最新预约，先帮助客户区分“别人期待的选择”和“自己愿意承担的选择”。', intendedCourse: null,
      confirmedFacts: ['刚结束一段管理工作', '目前有充足时间做探索'], aiQuestions: ['最担心哪一种未来结果'], paid: false, lastActivity: '今天 10:05', nextFollowup: null,
      lastFollowupAt: null, nextFollowupAt: null, followupStatus: '待跟进', notes: '',
    },
    {
      id: 'C00001313', createdAt: '2026-09-30', name: '程以宁', initials: '程', phone: '150****2608', status: '活跃', grade: 'B', gradeSource: '导师确认', mentorId: 'mentor-li', referrerName: '',
      need: '在亲密关系里常常不知道如何说出自己的需要。', helpExpectation: '希望练习更直接但不伤人的表达。', goal: '形成一套可以在关系里重复使用的表达句式。', brief: '客户愿意做具体练习，接待时可从最近一次没有说出口的需要开始。', intendedCourse: '镜像技术',
      confirmedFacts: ['能识别自己常常先照顾别人', '愿意尝试角色练习'], aiQuestions: ['对方的反馈是否会影响练习意愿'], paid: false, lastActivity: '昨天 13:25', nextFollowup: '2026-10-08',
      lastFollowupAt: '2026-09-30', nextFollowupAt: '2026-10-08', followupStatus: '跟进中', notes: '下一次练习具体表达。',
    },
    {
      id: 'C00001314', createdAt: '2026-09-18', name: '方知行', initials: '方', phone: '150****2609', status: '已完成', grade: 'S', gradeSource: '导师确认', mentorId: 'mentor-chen', referrerName: '',
      need: '希望从长期内耗中恢复行动力。', helpExpectation: '想建立更稳定的自我支持方式。', goal: '完成一轮自我观察与行动练习。', brief: '客户已经完成阶段性服务，并形成了可持续的行动记录。', intendedCourse: '觉塑',
      confirmedFacts: ['完成了四周练习', '能主动识别内耗循环'], aiQuestions: [], paid: true, lastActivity: '9 月 26 日', nextFollowup: null,
      lastFollowupAt: '2026-09-26', nextFollowupAt: null, followupStatus: '已完成', notes: '阶段目标已完成。',
    },
    {
      id: 'C00001315', createdAt: '2026-09-29', name: '乔念安', initials: '乔', phone: '150****2610', status: '活跃', grade: 'A', gradeSource: '导师确认', mentorId: 'mentor-li', referrerName: '苏晚晴',
      need: '面对重要决定时容易反复比较，迟迟无法行动。', helpExpectation: '想找到适合自己的判断方式。', goal: '用一次具体决定练习建立判断标准。', brief: '客户的困难集中在选择过程，后续可围绕一个正在发生的决定做现场拆解。', intendedCourse: null,
      confirmedFacts: ['正在考虑是否换城市', '愿意记录每个选项的代价'], aiQuestions: ['最担心承担哪一种结果'], paid: false, lastActivity: '昨天 11:00', nextFollowup: '2026-10-05',
      lastFollowupAt: '2026-09-29', nextFollowupAt: '2026-10-05', followupStatus: '待跟进', notes: '先完成决定记录表。',
    },
    {
      id: 'C00001316', createdAt: '2026-09-27', name: '林予墨', initials: '林', phone: '150****2611', status: '活跃', grade: 'B', gradeSource: 'AI建议', mentorId: 'mentor-chen', referrerName: '',
      need: '刚进入新团队，对自己的位置和边界不太确定。', helpExpectation: '希望更快适应新的工作关系。', goal: '识别团队中的关键关系并找到沟通入口。', brief: '客户处在环境变化期，适合先从一段具体工作互动开始，看见自己的反应模式。', intendedCourse: '东方领导力',
      confirmedFacts: ['入职新团队不到两个月', '已经遇到一次职责边界冲突'], aiQuestions: ['是否有稳定的支持对象'], paid: false, lastActivity: '9 月 30 日', nextFollowup: '2026-10-06',
      lastFollowupAt: '2026-09-27', nextFollowupAt: '2026-10-06', followupStatus: '跟进中', notes: '确认团队沟通中的具体场景。',
    },
    {
      id: 'C00001317', createdAt: '2026-10-04', name: '叶清越', initials: '叶', phone: '150****2612', status: '活跃', grade: 'C', gradeSource: 'AI建议', mentorId: null, referrerName: '',
      need: '做了很多准备，却一直没有真正发布自己的作品。', helpExpectation: '希望有人陪我完成第一次公开。', goal: '在本周完成一个小作品并得到反馈。', brief: '首次预约适合聚焦“第一次公开”的阻力和最小行动，不急于讨论长期品牌规划。', intendedCourse: null,
      confirmedFacts: ['已经积累了不少素材', '愿意接受一次小范围反馈'], aiQuestions: ['最担心别人看到什么'], paid: false, lastActivity: '今天 10:30', nextFollowup: null,
      lastFollowupAt: null, nextFollowupAt: null, followupStatus: '待跟进', notes: '',
    },
    {
      id: 'C00001318', createdAt: '2026-09-25', name: '许安然', initials: '许', phone: '150****2613', status: '活跃', grade: 'A', gradeSource: '导师确认', mentorId: 'mentor-qiao', referrerName: '',
      need: '想发展副业，但总在学习和执行之间来回摇摆。', helpExpectation: '希望确认一个能坚持三个月的计划。', goal: '选定一个方向并完成第一轮市场验证。', brief: '客户已有多个想法，服务时优先帮助其缩小范围并确认可验证的下一步。', intendedCourse: '东方领导力',
      confirmedFacts: ['已有一个可测试的服务想法', '每周可以投入固定时间'], aiQuestions: ['愿意放弃哪些暂时不重要的方向'], paid: false, lastActivity: '9 月 29 日', nextFollowup: '2026-10-06',
      lastFollowupAt: '2026-09-25', nextFollowupAt: '2026-10-06', followupStatus: '待跟进', notes: '需要补充本次服务记录。',
    },
  ],
  appointments: [
    { id: 'A-20261004-01', customerId: 'C00001305', topic: '人生方向', submittedAt: '20 分钟前', description: '最近总觉得卡住了，工作和生活都没有明确方向。', expectation: '希望有人帮我先把问题说清楚。', status: 'WAIT_ASSIGN', mentorId: null, assignedMentorId: null, followupHandled: false, followupInfoCompleted: false, createdAt: '2026-10-04', source: '解忧小屋' },
    { id: 'A-20261004-02', customerId: 'C00001301', topic: '亲密关系', submittedAt: '昨天 15:10', description: '每次沟通最后都会变成争吵，不知道从哪里开始改变。', expectation: '想先学习一次不升级冲突的沟通。', status: 'FOLLOWING', mentorId: 'mentor-zhang', assignedMentorId: 'mentor-zhang', followupHandled: false, followupInfoCompleted: false, createdAt: '2026-09-30', source: '解忧小屋' },
    { id: 'A-20261003-07', customerId: 'C00001276', topic: '个人成长', submittedAt: '10 月 3 日', description: '知道应该行动，但总是拖到最后又开始自责。', expectation: '想找到能真正开始的方法。', status: 'WAIT_FEEDBACK', mentorId: 'mentor-li', assignedMentorId: 'mentor-li', followupHandled: true, followupInfoCompleted: false, createdAt: '2026-09-28', source: '解忧小屋' },
    { id: 'A-20261002-11', customerId: 'C00001298', topic: '人生方向', submittedAt: '10 月 2 日', description: '离婚以后，忽然不知道接下来要怎么安排生活。', expectation: '希望有人陪我把接下来的路理一理。', status: 'COMPLETED', mentorId: 'mentor-zhang', assignedMentorId: 'mentor-zhang', followupHandled: true, followupInfoCompleted: true, createdAt: '2026-09-20', completedAt: '2026-10-02', source: '解忧小屋' },
    { id: 'A-20261004-03', customerId: 'C00001306', topic: '职业方向', submittedAt: '今天 09:20', description: '工作几年后开始怀疑自己是不是走错了方向。', expectation: '想有人帮我把纠结的几件事拆开。', status: 'WAIT_ASSIGN', mentorId: null, assignedMentorId: null, followupHandled: false, followupInfoCompleted: false, createdAt: '2026-10-04', source: '解忧小屋' },
    { id: 'A-20261004-04', customerId: 'C00001307', topic: '行动启动', submittedAt: '今天 09:45', description: '长期拖延重要的事，越拖越不敢开始。', expectation: '希望找到一个今天就能开始的行动。', status: 'WAIT_ASSIGN', mentorId: null, assignedMentorId: null, followupHandled: false, followupInfoCompleted: false, createdAt: '2026-10-04', source: '解忧小屋' },
    { id: 'A-20261003-08', customerId: 'C00001308', topic: '职业转型', submittedAt: '昨天 11:15', description: '准备离开熟悉的行业，但对新选择没有把握。', expectation: '想把转型计划变得更具体。', status: 'FOLLOWING', mentorId: 'mentor-qiao', assignedMentorId: 'mentor-qiao', followupHandled: false, followupInfoCompleted: false, createdAt: '2026-10-03', source: '解忧小屋' },
    { id: 'A-20261002-12', customerId: 'C00001309', topic: '家庭沟通', submittedAt: '10 月 2 日', description: '和家人沟通时总是先防御，事后又觉得可惜。', expectation: '希望练习更稳定地表达边界。', status: 'FOLLOWING', mentorId: 'mentor-zhang', assignedMentorId: 'mentor-zhang', followupHandled: false, followupInfoCompleted: false, createdAt: '2026-10-02', source: '解忧小屋' },
    { id: 'A-20261001-09', customerId: 'C00001310', topic: '情绪稳定', submittedAt: '10 月 1 日', description: '最近情绪起伏明显，工作时很难集中。', expectation: '希望找到让自己先稳定下来的方法。', status: 'WAIT_FEEDBACK', mentorId: 'mentor-chen', assignedMentorId: 'mentor-chen', followupHandled: true, followupInfoCompleted: false, createdAt: '2026-10-01', source: '解忧小屋' },
    { id: 'A-20260930-10', customerId: 'C00001311', topic: '职业行动', submittedAt: '9 月 30 日', description: '完成一次职业方向梳理，准备开始新的项目。', expectation: '希望确认行动节奏和优先级。', status: 'COMPLETED', mentorId: 'mentor-qiao', assignedMentorId: 'mentor-qiao', followupHandled: true, followupInfoCompleted: true, createdAt: '2026-09-22', completedAt: '2026-09-30', source: '解忧小屋' },
    { id: 'A-20261004-05', customerId: 'C00001312', topic: '人生选择', submittedAt: '今天 10:05', description: '从团队管理岗位离开后，对下一步选择很犹豫。', expectation: '想先把自己真正想要的生活方式说清楚。', status: 'WAIT_ASSIGN', mentorId: null, assignedMentorId: null, followupHandled: false, followupInfoCompleted: false, createdAt: '2026-10-04', source: '解忧小屋' },
    { id: 'A-20260930-11', customerId: 'C00001313', topic: '关系表达', submittedAt: '9 月 30 日', description: '在亲密关系里常常不知道如何说出自己的需要。', expectation: '希望练习更直接但不伤人的表达。', status: 'FOLLOWING', mentorId: 'mentor-li', assignedMentorId: 'mentor-li', followupHandled: false, followupInfoCompleted: false, createdAt: '2026-09-30', source: '解忧小屋' },
    { id: 'A-20260926-06', customerId: 'C00001314', topic: '自我支持', submittedAt: '9 月 26 日', description: '希望从长期内耗中恢复行动力。', expectation: '想建立更稳定的自我支持方式。', status: 'COMPLETED', mentorId: 'mentor-chen', assignedMentorId: 'mentor-chen', followupHandled: true, followupInfoCompleted: true, createdAt: '2026-09-18', completedAt: '2026-09-26', source: '解忧小屋' },
    { id: 'A-20260929-12', customerId: 'C00001315', topic: '人生决定', submittedAt: '9 月 29 日', description: '面对重要决定时容易反复比较，迟迟无法行动。', expectation: '想找到适合自己的判断方式。', status: 'WAIT_FEEDBACK', mentorId: 'mentor-li', assignedMentorId: 'mentor-li', followupHandled: true, followupInfoCompleted: false, createdAt: '2026-09-29', source: '解忧小屋' },
    { id: 'A-20260927-14', customerId: 'C00001316', topic: '团队关系', submittedAt: '9 月 27 日', description: '刚进入新团队，对自己的位置和边界不太确定。', expectation: '希望更快适应新的工作关系。', status: 'FOLLOWING', mentorId: 'mentor-chen', assignedMentorId: 'mentor-chen', followupHandled: false, followupInfoCompleted: false, createdAt: '2026-09-27', source: '解忧小屋' },
    { id: 'A-20261004-06', customerId: 'C00001317', topic: '作品表达', submittedAt: '今天 10:30', description: '做了很多准备，却一直没有真正发布自己的作品。', expectation: '希望有人陪我完成第一次公开。', status: 'WAIT_ASSIGN', mentorId: null, assignedMentorId: null, followupHandled: false, followupInfoCompleted: false, createdAt: '2026-10-04', source: '解忧小屋' },
    { id: 'A-20260925-15', customerId: 'C00001318', topic: '副业计划', submittedAt: '9 月 25 日', description: '想发展副业，但总在学习和执行之间来回摇摆。', expectation: '希望确认一个能坚持三个月的计划。', status: 'WAIT_FEEDBACK', mentorId: 'mentor-qiao', assignedMentorId: 'mentor-qiao', followupHandled: true, followupInfoCompleted: false, createdAt: '2026-09-25', source: '解忧小屋' },
  ],
  sessions: [
    { id: 'S-00081', customerId: 'C00001298', mentorId: 'mentor-zhang', type: '免费初聊', date: '2026-10-02 19:30', duration: 45, topic: '离婚后的生活重建', note: '用户希望先恢复生活节奏，再处理职业方向。', result: '需要继续跟进', nextStep: '一周内回访上周约定的生活行动', followupDate: '2026-10-06', aiSummary: '用户当前最优先的不是立即做职业选择，而是重新建立生活秩序和可控感。' },
    { id: 'S-00079', customerId: 'C00001276', mentorId: 'mentor-li', type: '体验沟通', date: '2026-09-28 14:00', duration: 40, topic: '把想做的事变成行动', note: '一起拆出了本周第一步：完成作品集目录。', result: '有进一步服务需求', nextStep: '确认是否进入镜像技术课程', followupDate: '2026-10-04', aiSummary: '用户对“有人陪着完成第一步”有明确需求，课程匹配度较高。' },
    { id: 'S-00083', customerId: 'C00001308', mentorId: 'mentor-qiao', type: '首次沟通', date: '2026-10-03 11:15', duration: 50, topic: '从熟悉行业走向新方向', note: '梳理了客户已有能力和想验证的新行业。', result: '需要继续关注', nextStep: '完成一页能力盘点，带着具体问题进入下一次沟通。', followupDate: '2026-10-07', aiSummary: '客户并非缺少能力，而是需要把转型愿望转成可验证的路径。' },
    { id: 'S-00084', customerId: 'C00001309', mentorId: 'mentor-zhang', type: '关系沟通', date: '2026-10-02 18:30', duration: 45, topic: '家庭对话中的防御反应', note: '回看了一次与家人的真实对话，找到几个自动防御的瞬间。', result: '需要继续关注', nextStep: '练习一次先表达感受、再表达边界的对话。', followupDate: '2026-10-06', aiSummary: '客户已经能看见自己的自动反应，下一步是把觉察带回一段具体关系。' },
    { id: 'S-00085', customerId: 'C00001310', mentorId: 'mentor-chen', type: '情绪支持', date: '2026-10-01 15:40', duration: 40, topic: '识别情绪波动的前置信号', note: '确认了睡眠不足和工作切换是近期的两个触发场景。', result: '需要补充记录', nextStep: '记录三次情绪变化，下一次一起看触发与恢复。', followupDate: '2026-10-05', aiSummary: '客户需要的第一步不是压住情绪，而是更早识别身体和环境信号。' },
  ],
  followups: [
    { id: 'F-00041', customerId: 'C00001298', ownerId: 'mentor-zhang', date: '2026-10-06', channel: '微信', note: '询问生活节奏行动后的变化，不急着介绍课程。', status: '待跟进', stage: '考虑中' },
    { id: 'F-00042', customerId: 'C00001301', ownerId: 'mentor-zhang', date: '2026-10-04', channel: '电话', note: '跟进上次记录的触发点，确认是否愿意做一次沟通练习。', status: '待跟进', stage: '潜在需求' },
    { id: 'F-00043', customerId: 'C00001276', ownerId: 'mentor-li', date: '2026-10-04', channel: '微信', note: '确认课程时间条件和长期学习意愿。', status: '待跟进', stage: '需求明确' },
    { id: 'F-00039', customerId: 'C00001254', ownerId: 'mentor-li', date: '2026-09-28', channel: '微信', note: '完成一期后发送社群介绍。', status: '已完成', stage: '已成交' },
    { id: 'F-00044', customerId: 'C00001308', ownerId: 'mentor-qiao', date: '2026-10-07', channel: '微信', note: '查看能力盘点结果，确认转型验证的第一个小步骤。', status: '待跟进', stage: '需求明确' },
    { id: 'F-00045', customerId: 'C00001309', ownerId: 'mentor-zhang', date: '2026-10-06', channel: '电话', note: '询问边界表达练习后的真实反馈。', status: '待跟进', stage: '潜在需求' },
    { id: 'F-00046', customerId: 'C00001310', ownerId: 'mentor-chen', date: '2026-10-05', channel: '微信', note: '回看三次情绪变化记录，确认最需要支持的场景。', status: '待跟进', stage: '需求明确' },
    { id: 'F-00047', customerId: 'C00001316', ownerId: 'mentor-chen', date: '2026-10-06', channel: '微信', note: '确认团队边界冲突中的沟通对象和下一步。', status: '待跟进', stage: '潜在需求' },
  ],
  products: [
    { id: 'P-001', name: '觉塑', system: 'ASVA 成长体系', audience: '想重新建立内在稳定感的人', cycle: '8 周', format: '小组 + 练习', status: '在售', summary: '从身体感受、情绪识别和行动练习开始，逐步恢复对自己的感知和选择。', fit: ['主体性', '长期重复模式', '方向感不足'] },
    { id: 'P-002', name: '镜像技术', system: 'ASVA 成长体系', audience: '需要改善表达与关系互动的人', cycle: '6 周', format: '小组工作坊', status: '在售', summary: '帮助参与者看见互动中的惯性反应，练习更清楚地表达和回应。', fit: ['关系沟通', '表达困难', '冲突反复'] },
    { id: 'P-003', name: '表达性艺术治疗', system: '专业成长', audience: '希望拓展自我表达方式的人', cycle: '4 周', format: '主题工作坊', status: '筹备中', summary: '通过非语言的创作和观察，打开对经验的另一种理解入口。', fit: ['自我表达', '情绪探索', '创造力'] },
    { id: 'P-004', name: '东方领导力', system: '专业成长', audience: '正在承担团队与组织责任的人', cycle: '10 周', format: '课程 + 督导', status: '在售', summary: '从自我关系、关系判断和组织行动三个层面，练习更稳定的领导方式。', fit: ['职业转型', '团队管理', '长期成长'] },
  ],
  enrollments: [
    { id: 'E-00012', customerId: 'C00001298', productId: 'P-001', paid: true, amount: 3980, date: '2026-09-20', status: '学习中' },
    { id: 'E-00013', customerId: 'C00001276', productId: 'P-002', paid: true, amount: 2680, date: '2026-09-10', status: '学习中' },
    { id: 'E-00009', customerId: 'C00001254', productId: 'P-002', paid: true, amount: 2680, date: '2026-08-20', status: '已完成' },
  ],
  profiles: [{
    id: 'profile-C00001298', customerId: 'C00001298', updatedAt: '2026-10-04T10:40:00.000Z', schemaVersion: 'v0.4',
    fields: { age: 36, city: '杭州', occupation: '设计', marital_status: '已婚', children_summary: '1个8岁女儿', relationship_conflicts: '夫妻关系长期冷战', hobbies: ['瑜伽', '旅行'], core_values: ['家庭完整', '稳定'], current_goal: '改善夫妻沟通' },
    fieldMeta: Object.fromEntries(['age', 'city', 'occupation', 'marital_status', 'children_summary', 'relationship_conflicts', 'hobbies', 'core_values', 'current_goal'].map((field) => [field, { source: 'MENTOR_CONFIRMED', confidence: 1, confirmed: true, updatedAt: '2026-10-04T10:40:00.000Z' }])),
  }],
  profileChanges: [],
}
